### ISSUE TITLE
demo fail

### ISSUE THREAD

**Issue by ludvik** [AssemblyAI/realtime-transcription-browser-js-example#5]
I tried to test the demo. Upgraded my account, paste key into server.js

When I click "Start" on "localhost:3000", server claims error:

(base) ➜  realtime-transcription-browser-js-example git:(master) ✗ npm run server

> audio-testing@1.0.0 server
> node ./js/server.js

Server is running on port 8000

/Users/ludvik/arsenal/realtime-transcription-browser-js-example/js/server.js:17
    const {response: {status, data}} = error;
                      ^

TypeError: Cannot read properties of undefined (reading 'status')
    at /Users/ludvik/arsenal/realtime-transcription-browser-js-example/js/server.js:17:23
    at Layer.handle [as handle_request] (/Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/express/lib/router/index.js:275:10)
    at cors (/Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/cors/lib/index.js:188:7)
    at /Users/ludvik/arsenal/realtime-transcription-browser-js-example/node_modules/cors/lib/index.js:224:17

Node.js v17.8.0

I think I already did everything REAMD told.

**Comment by anniepauline** [comment]
would like to work on this issue!

**Comment by MLawlz** [comment]
Hey @ludvik @anniepauline! I'm going to mark this issue as stale/closed since the project has been updated a lot since April, and it'd be better to track any new errors that are encountered in new issues. If you do run into any problems, feel free to reach out to us at support@assemblyai.com or create an Issue here for us to review!
